#!@zsh@

setopt NO_HUP

function die() {
    @tmux@ detach
    exit $1
}

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | @fzf@ --reverse --prompt='pass> ')

[[ -n $password ]] || die 0

@pass@ show "$password" | @head@ -n1 | @wl-copy@ --trim-newline
die 0
