# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [];

  hardware.enableRedistributableFirmware = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "kvm-intel" "dm_snapshot" "dm_integrity" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks = {
    devices = {
      "seaborgium_pv" = {
        device = "/dev/disk/by-uuid/329f66f4-0181-4b3b-ac2d-f305383e08cf";
      };
    };
    cryptoModules = [
      "aegis256" "aegis256_aesni" "dm_integrity" "aes"
      "aes_generic" "aes_x86_64" "xts" "sha256" "sha512"
      "dm_bufio" "algif_aead" "algif_skcipher" "md4"
      "algif_hash" "arc4" "ctr" "cbc" "authenc" "cmac" "ccm"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a1dcc9cc-a7b5-47db-8ea0-85b8cb81b120";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12497b5c-85d7-46aa-99d7-4007cad2938d";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/seaborgium/swap"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
