# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [];

  hardware.enableRedistributableFirmware = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "kvm-intel" "dm_snapshot" "dm_integrity" ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot = {
    enable = true;
    editor = true;
  };

  boot.initrd.luks = {
    devices = {
      "bohrium-tmp_pv" = {
        device = "/dev/disk/by-uuid/03cdff41-e1e0-4767-bc42-52b4c9542f33";
      };
    };
    cryptoModules = [
      "dm_integrity" "aes" "aes_generic" "aes_x86_64"  "sha256"
      "aegis128" "aegos128_aesni"
      "dm_bufio" "algif_aead" "algif_skcipher" "algif_hash" "authenc"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/48a9f9ca-4460-4889-9b9c-f164afa69b79";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F2D7-8671";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/bohrium-tmp/swap"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
