[package]
name = "wolkenheim-secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive", "cargo", "unicode", "env"] }
ctap-hid-fido2 = "3.5.0"
service-binding = "1.1.0"
