# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "obs-cli-unstable-${version}";
  version = "2020-02-16";
  rev = "9cb109077f39864ca239bb8e9e4e77009ab4739c";

  goPackagePath = "github.com/muesli/obs-cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/muesli/obs-cli";
    sha256 = "1gcskjsv3fj2r2cy6x6lbr38s692fb8z63d19yd0b4lan4ll0ibq";
  };

  goDeps = ./deps.nix;
}
