# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "c3dd95aea9779669bb3daafbd84ee0530c8ce1c1";
      sha256 = "0ny2r232jivr1d611gavz5ws3y3r8b5cd2als9544lr0v0m5cikw";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "9e1e4717f8567d7ead72d070d064ad17d444a67e";
      sha256 = "1pzyvzbpd9vs4qvj2hd141hk6ppw9lxygw7sy5770raa9rml1ynl";
    };
  }
  {
    goPackagePath = "github.com/muesli/go-obs-websocket";
    fetch = {
      type = "git";
      url = "https://github.com/muesli/go-obs-websocket";
      rev = "501318ebaadbc6db61106afc8f93c8d1ebd7ada9";
      sha256 = "0k9agrib7zyp6i4x5d7jdimpmnv9i78znsxml5xsp405d0nbsyd4";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "86f8bfd7fef868a174e1b606783bd7f5c82ddf8f";
      sha256 = "0qx2wm34sm92amxackxl1vlwxlhvrpcwr1h474601szb1c49mlk1";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "85dd5c8bc61cfa382fecd072378089d4e856579d";
      sha256 = "1gmznqipnr4g9hjf1ihwdfd6zh4klirwm5npsn278qq9v807c4xc";
    };
  }
]
