# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.luks.devices = [ { device = "/dev/sda1"; name = "pv"; preLVM = true; allowDiscards = true; } ];
  boot.initrd.luks.cryptoModules = [ "aegis256" "aegis256_aesni" "dm_integrity" "aes"
                                     "aes_generic" "aes_x86_64" "xts" "sha256" "sha512"
                                     "dm_bufio" "algif_aead" "algif_skcipher" "md4"
                                     "algif_hash" "arc4" "ctr" "cbc" "authenc" "cmac" "ccm"
                                   ];
  boot.initrd.supportedFilesystems = [ "ext4" ];
  boot.initrd.kernelModules = [ "kvm-intel" "dm_snapshot" "dm_integrity" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
  };

  boot.resumeDevice = "/dev/freyr/swap";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/70b3f5c9-8b23-4485-8b59-a16b8d433695";
      fsType = "ext4";
      options = [ "discard" "relatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2F99-3DFD";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/freyr/swap"; }
    ];
}
