{
 "title": "boron",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "boron" }
  ]
 },
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$server\"}-node_boot_time_seconds{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{instance=~\"$server\"} + node_memory_Buffers_bytes{instance=~\"$server\"} + node_memory_Cached_bytes{instance=~\"$server\"} + node_zfs_arc_size{instance=~\"$server\"}) / node_memory_MemTotal_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Min Free disk space",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{fstype=\"zfs\",instance=~\"$server\"}/node_filesystem_size_bytes{fstype=\"zfs\",instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "System load normalized",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}/(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}/(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}/(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU busy%",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\"}[15s])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemFree_bytes{instance=~\"$server\"}+node_memory_Buffers_bytes{instance=~\"$server\"}+node_memory_Cached_bytes{instance=~\"$server\"} + node_zfs_arc_size{instance=~\"$server\"})/node_memory_MemTotal_bytes{instance=~\"$server\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "cpu busy %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\"}[15s])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "/proc/vmstat pgmajfault",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{instance=\"$server\"}[1m])",
     "legendFormat": "pgmajfault rate"
    }
   ]
  },
  {
   "title": "IO Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Latency per device",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$server\"}[15s])/(irate(node_disk_reads_completed_total{instance=~\"$server\"}[15s]) + irate(node_disk_writes_completed_total{instance=~\"$server\"}[15s]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk I/O per minute",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (device) (rate(node_disk_read_bytes_total{instance=~\"$server\"}[1m]))",
       "legendFormat": "{{device}} bytes read"
      },
      {
       "expr": "sum by (device) (rate(node_disk_written_bytes_total{instance=~\"$server\"}[1m]))",
       "legendFormat": "{{device}} bytes written"
      }
     ]
    }
   ]
  }
 ]
}