# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/boltdb/bolt";
    fetch = {
      type = "git";
      url = "https://github.com/boltdb/bolt";
      rev = "fd01fc79c553a8e99d512a07e8e0c63d4a3ccfc5";
      sha256 = "12f5swiwzcamk87r9j73nn7rmyyday7jkgzfh7x5wdg9blzhrir2";
    };
  }
  {
    goPackagePath = "github.com/cespare/xxhash";
    fetch = {
      type = "git";
      url = "https://github.com/cespare/xxhash";
      rev = "de209a9ffae3256185a6bb135d1a0ada7b2b5f09";
      sha256 = "12ad3z7ki9j07c4kx3ywkl6188i2afsjg7sl60wd21p6zkkpfjxq";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
]
