#!@zsh@

setopt NO_HUP

function die() {
    @tmux@ detach
    exit $1
}

password=$(@pass@ list -f | @fzf@ --reverse --prompt='pass> ')

[[ -n $password ]] || die 0

@pass@ show -o "$password" | @wl-copy@ --trim-newline
die 0
