#!@zsh@

prefix=@prefix@
DIR="${HOME}/.local/cache/pdftotext"

function laststatus() {
    return $?
}

function die() {
    @tmux@ detach
    exit $1
}

function _do_fzf() {
    FZF_DEFAULT_COMMAND="@fzf-dpt-candidates@ \"${DIR}\"" @fzf@ --read0 -e -d '\t' \
            --prompt='dptrp1> ' \
            --reverse \
            --preview-window right:75% \
            --preview 'v=$(echo {q} | @tr@ " " "|"); [ -n {} ] && @grep@ -E "^|$v" -i --color=always <'$DIR'/$(@stat@ -c "%d %i %Y %n" {1} | @b2sum@ | @cut@ -c 1-128)' \
    | @awk@ 'BEGIN {FS="\t"; OFS="\t"}; {print $1}'
}

file=$(_do_fzf)

laststatus || die 1
[[ -z "$file" ]] && die 0

case "$file" in
  @prefix@/*)
    path=Document/"${file#${prefix}/}"
    ;;
  *)
    path=Document/scratch/"$(@basename@ "${file}")"
    @dptrp1@ upload "${file}" "${path}"
    ;;
esac

(set -m; trap ':' 1; exec @dptrp1@ display-document "${path}" >/dev/null 2>&1) &!
die 0
