#!@zsh@

_profile="$1"

function do_sqlite() {
  @sqlite3@ -separator $'\t' "$1" | tr '\n' '\0'
  rm "$1"
}

@jq@ -j '.roots | .. | select(.url?) | .url + "\t" + .name + "\u0000"' < ${_profile}/Bookmarks
do_sqlite =(@cat@ ${_profile}/History) <<EOF
select url, title from (select url, title, last_visit_time from urls group by url) t order by last_visit_time desc
EOF
