#!@zsh@

if [[ "$1" == "search" ]]; then
    _url_mod=_duckduckgo
else
    _url_mod=_id
fi

setopt EXTENDED_GLOB
_profile_=( ~/.config/chromium/Default )
_profile="${_profile_[1]}"

function _do_fzf() {
    FZF_DEFAULT_COMMAND="@fzf-chrome-url-candidates@ \"$_profile\"" \
    @fzf@ --read0 --print0 -e -d '\t' \
          --no-sort \
          --reverse \
          --prompt="open${1+ }$1> " \
          --print-query \
          --expect='alt-enter,enter' \
          --preview-window up:1 \
          --preview 'v=$(echo {q} | tr " " "|"); echo {2..} | @grep@ -E "^|$v" -i --color=always' \
    | @awk@ 'BEGIN {FS="\t"; OFS="\t"}; {print $1}'
}

function laststatus() {
    case $? in
        0) return 0 ;;
        1) return 0 ;;
        *) return 1 ;;
    esac
}

function die() {
    @tmux@ detach
    exit $1
}

function chromium_running() {
    @pgrep@ -f 'chromium' >/dev/null
}

function _duckduckgo() {
    printf 'https://duckduckgo.com/?q=%s' "$*"
}

function _id() {
    printf "%s" "$*"
}

output=( "${(0)$(_do_fzf "$@")}" )
laststatus || die 1

case "${output[2]}" in
    alt-enter)
        cmd="${output[1]}"
        ;;
    enter)
        cmd="${output[3]}"
        ;;
esac

case "${cmd}" in
    \!*)
        _url_mod=_duckduckgo
        ;;
esac

[[ -z "$cmd" ]] && die 1

if chromium_running; then
    @chromium-unwrapped@ --new-window "$("$_url_mod" "$cmd")"
fi

die 0
