# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "git.torproject.org/pluggable-transports/goptlib.git";
    fetch = {
      type = "git";
      url = "https://git.torproject.org/pluggable-transports/goptlib";
      rev = "7d56ec4f381e8b1aedfda360594e35a5731b5337";
      sha256 = "0h8l60blbg9wmxx0na26vid0vd07cjj67afhlvrph68i1k8l1lin";
    };
  }
  {
    goPackagePath = "github.com/agl/ed25519";
    fetch = {
      type = "git";
      url = "https://github.com/agl/ed25519";
      rev = "5312a61534124124185d41f09206b9fef1d88403";
      sha256 = "1v8mhkf1m3ga5262s75vabskxvsw5rpqvi5nwhxwiv7gfk6h823i";
    };
  }
  {
    goPackagePath = "github.com/dchest/siphash";
    fetch = {
      type = "git";
      url = "https://github.com/dchest/siphash";
      rev = "34f201214d993633bb24f418ba11736ab8b55aa7";
      sha256 = "08s076y7vmjqnq7jz0762hkm896r6r31v8b31a3gy0n8rfa01k8k";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "0e37d006457bf46f9e6692014ba72ef82c33022c";
      sha256 = "1fj8rvrhgv5j8pmckzphvm3sqkzhcqp3idkxvgv13qrjdfycsa5r";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "26e67e76b6c3f6ce91f7c52def5af501b4e0f3a2";
      sha256 = "17bqkd64zksi1578lb10ls4qf5lbqs7shfjcc6bi97y1qz5k31c4";
    };
  }
]
