# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "obfs4-git-unstable-${version}";
  version = "2018-04-21";
  rev = "89c21805c212bcc2f5a0c4ffdadf424cbff1c7c9";

  goPackagePath = "git.torproject.org/pluggable-transports/obfs4.git";

  src = fetchgit {
    inherit rev;
    url = "https://git.torproject.org/pluggable-transports/obfs4";
    sha256 = "080x6jq4ndxcwbdnf80xskp95jgn45jfswz7p67m5vk0ix3jbr27";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
