#!@zsh@

_profile="$1"

function do_sqlite() {
  @sqlite3@ -separator $'\t' "$1" | tr '\n' '\0'
  rm "$1"
}

do_sqlite =(@cat@ ${_profile}/places.sqlite) <<EOF
select url, title from (select url, title, max(last_visit_date) as last_visit_date from moz_places group by url) t order by last_visit_date desc
EOF
